
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int print = 8;
  public static final int edge = 10;
  public static final int directed = 6;
  public static final int adjacency = 12;
  public static final int EOF = 0;
  public static final int vertex = 9;
  public static final int colon = 3;
  public static final int GRAPH = 2;
  public static final int ID = 11;
  public static final int invalido = 13;
  public static final int error = 1;
  public static final int undirected = 7;
  public static final int arrow = 5;
  public static final int line = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "GRAPH",
  "colon",
  "line",
  "arrow",
  "directed",
  "undirected",
  "print",
  "vertex",
  "edge",
  "ID",
  "adjacency",
  "invalido"
  };
}

